### PR TITLE
Add trim_log_values option to config to abbreviate long strings and lists

### PR DESCRIPTION
**Pull request by ferrouswheel**
Following on from bcb/jsonrpcserver#65

Part of me thought about storing `.trim_log_values` on the PreparedRequest object, but I wasn't sure...

### CODE REVIEW

**Comment by bcb** [comment]
Thanks @ferrouswheel.

I'm planning to remove the config module, as in the server lib.

I think it's better to make the client object configurable like this:

```python
client = HTTPClient("http://example.com", trim_log_values=True)
```

Would that work for you?

**Comment by ferrouswheel** [comment]
We use the convenient `jsonrpcclient.request` method a lot, so if it's placed as an initializer on the Client class constructor, then I'd want to add it to the request method too.

But that has the signature `def request(endpoint, method, *args, **kwargs)` so it'd prevent `trim_log_values` from being a valid JSON-RPC parameter. It could be prefixed with underscores to make it more unlikely... or maybe `endpoint` could be checked to see if it is a dictionary, and if so, it'd get expanded into kwargs for the constructor?

**Comment by bcb** [comment]
I'm thinking for that we can use a separate named param, like this:

```python
def request(endpoint, method, trim_log_values=False, *args, **kwargs):
    return HTTPClient(endpoint, trim_log_values=trim_log_values).request(method, *args, **kwargs)
```

Will try it out.

**Comment by bcb** [comment]
I've created PR #78 for this, which lets you configure trim_log_values by passing parameter values rather than the config module. Can you let me know if it will work for you? If so, I'll merge and release a new version tomorrow.

**Comment by ferrouswheel** [comment]
Thanks - it would work fine for me, though I have concern about it potentially causing issues for future users as mentioned on the PR.

**Pull request merged**
